# Generated by Django 3.2.18 on 2023-04-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferenceroom',
            old_name='capaciy',
            new_name='capacity',
        ),
    ]
